### ISSUE TITLE
Error on RPi4 with Ubuntu

### ISSUE THREAD

**Issue by FPSychotic** [leigh-johnson/rpi-deep-pantilt#21]
* rpi-deep-pantilt version:master
* Python version:3.6.9
* TensorFlow version:oral tpu runtime
* Operating System:ubuntu 18.04

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

Hi Im trying install your project on a RPi4 4gb with Ubuntu, but it looks is asking by Raspbian
 pip install https://github.com/leigh-johnson/Tensorflow-bin/blob/master/tensorflow-2.0.0-cp37-cp37m-linux_armv7l.whl?raw=true
ERROR: tensorflow-2.0.0-cp37-cp37m-linux_armv7l.whl is not a supported wheel on this platform.


```
(.venv) ubuntu@ubuntu:~/rpi-deep-pantilt$ python3 -m pip install rpi-deep-pantilt
ERROR: Could not find a version that satisfies the requirement rpi-deep-pantilt (from versions: none)
ERROR: No matching distribution found for rpi-deep-pantilt

**Comment by leigh-johnson** [comment]
Hey! Thanks for reporting this. Unfortunately, I'm only able to support Raspbian as the target platform for the Pi right now. 

I might support other platforms (Ubuntu / Gentoo) but I don't have a timeline on when that would be.
