### ISSUE TITLE
pipeline.config

### ISSUE THREAD

**Issue by natxopedreira** [leigh-johnson/rpi-deep-pantilt#34]
Hello

Im trying to compile re-train myself a model using [facessd_mobilenet_v2_quantized_320x320_open_image_v4](http://download.tensorflow.org/models/object_detection/facessd_mobilenet_v2_quantized_320x320_open_image_v4.tar.gz) but im having problems using the config file provided on tensorflow model repo trowing an error about `RandomCropToAspectRatio/stack failed to run.... `[https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/facessd_mobilenet_v2_quantized_320x320_open_image_v4.config](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/facessd_mobilenet_v2_quantized_320x320_open_image_v4.config)

Can you please share your pipeline.config so i can compare and look for differences?

Thank you!!

**Comment by leigh-johnson** [comment]
Hey @natxopedreira!

Unfortunately, I didn't re-train the FaceSSD model (so I don't have a working pipeline.config to share). :( You might have better luck asking in the https://github.com/tensorflow/models/ repo. Hope you're able to get this working!
